create database Text1;
create database Text2;
create database Text3;
create table Text1.Technical(BookName varchar(50), BookAuthor varchar(50), NoOfPgs Integer, Publisher varchar(50));
create table Text1.Management(BookName varchar(50), BookAuthor varchar(50), NoOfPgs Integer, Publisher varchar(50));
create table Text1.Sports(BookName varchar(50), BookAuthor varchar(50), NoOfPgs Integer, Publisher varchar(50));
create table Text2.Technical(BookName varchar(50), BookAuthor varchar(50), NoOfPgs Integer, Publisher varchar(50));
create table Text2.Management(BookName varchar(50), BookAuthor varchar(50), NoOfPgs Integer, Publisher varchar(50));
create table Text2.Sports(BookName varchar(50), BookAuthor varchar(50), NoOfPgs Integer, Publisher varchar(50));
create table Text3.Technical(BookName varchar(50), BookAuthor varchar(50), NoOfPgs Integer, Publisher varchar(50));
create table Text3.Management(BookName varchar(50), BookAuthor varchar(50), NoOfPgs Integer, Publisher varchar(50));
create table Text3.Sports(BookName varchar(50), BookAuthor varchar(50), NoOfPgs Integer, Publisher varchar(50));
insert into Text1.Technical values ("BookTech1","AuthorTech1",150,"TechPublish1"),("BookTech2","AuthorTech2",180,"TechPublish2"),("BookTech3","AuthorTech3",230,"TechPublish3");
insert into Text1.Management values ("BookManage1","AuthorManage1",160,"ManagePublish1"),("BookManage2","AuthorManage2",630,"ManagePublish2"),("BookManage3","AuthorManage3",560,"ManagePublish3");
insert into Text1.Sports values ("BookSports1","AuthorSports1",430,"SportsPublish1"),("BookSports2","AuthorSports2",430,"SportsPublish2"),("BookSports3","AuthorSports3",430,"SportsPublish3");
insert into Text2.Technical values ("BookTech1","AuthorTech1",150,"TechPublish1"),("BookTech2","AuthorTech2",180,"TechPublish2"),("BookTech3","AuthorTech3",230,"TechPublish3");
insert into Text2.Management values ("BookManage1","AuthorManage1",160,"ManagePublish1"),("BookManage2","AuthorManage2",630,"ManagePublish2"),("BookManage3","AuthorManage3",560,"ManagePublish3");
insert into Text2.Sports values ("BookSports1","AuthorSports1",430,"SportsPublish1"),("BookSports2","AuthorSports2",430,"SportsPublish2"),("BookSports3","AuthorSports3",430,"SportsPublish3");
insert into Text3.Technical values ("BookTech1","AuthorTech1",150,"TechPublish1"),("BookTech2","AuthorTech2",180,"TechPublish2"),("BookTech3","AuthorTech3",230,"TechPublish3");
insert into Text3.Management values ("BookManage1","AuthorManage1",160,"ManagePublish1"),("BookManage2","AuthorManage2",630,"ManagePublish2"),("BookManage3","AuthorManage3",560,"ManagePublish3");
insert into Text3.Sports values ("BookSports1","AuthorSports1",430,"SportsPublish1"),("BookSports2","AuthorSports2",430,"SportsPublish2"),("BookSports3","AuthorSports3",430,"SportsPublish3");
select * from Text1.Technical;
select * from Text1.Management;
select * from Text1.Sports;
select * from Text2.Technical;
select * from Text2.Management;
select * from Text2.Sports;
select * from Text3.Technical;
select * from Text3.Management;
select * from Text3.Sports;
